# Scrub all entry in cache tables.

drush sqlq "truncate cache;"
drush sqlq "truncate cache_block;"
drush sqlq "truncate cache_page;"
drush sqlq "truncate cache_views;"
drush sqlq "truncate cache_bootstrap;"
drush sqlq "truncate cache_coder;"
drush sqlq "truncate cache_content;"
drush sqlq "truncate cache_field;"
drush sqlq "truncate cache_filter;"
drush sqlq "truncate cache_form;"
drush sqlq "truncate cache_image;"
drush sqlq "truncate cache_libraries;"
drush sqlq "truncate cache_menu;"
drush sqlq "truncate cache_oembed;"
drush sqlq "truncate cache_path;"
drush sqlq "truncate cache_token;"
drush sqlq "truncate cache_views_data;"
drush sqlq "truncate ctools_css_cache;"
drush sqlq "truncate ctools_object_cache;"
drush sqlq "truncate imagecache_preset;"
drush sqlq "truncate views_object_cache;"
drush cc all

echo "Done"
